# Generated by Django 5.0.1 on 2024-03-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
    ]
