# Generated by Django 5.0.2 on 2024-03-18 03:23

import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_country_servicepost_state_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.city'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.country'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=service.models.service_path),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.state'),
        ),
    ]
