# Generated by Django 5.0.2 on 2024-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicepostcomment_serviceprovideravailability'),
        ('service', '0006_alter_servicepost_city_alter_servicepost_country_and_more'),
    ]

    operations = [
    ]
