# Generated by Django 5.0.2 on 2024-03-19 05:20

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_merge_20240319_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=service.models.service_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelledbycustomer', 'CancelledByCustomer'), ('cancelledbyprovider', 'CancelledByProvider')], default='pending', max_length=50)),
                ('appointment_time', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='country',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='state',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceprovideravailability',
            name='service_post',
        ),
        migrations.RemoveField(
            model_name='servicepostcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceprovideravailability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userservicerating',
            name='user_service',
        ),
    ]
