# Generated by Django 5.0.2 on 2024-03-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_providerservice_address_providerservice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
    ]
