# Generated by Django 5.0.2 on 2024-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_servicerating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
