# Generated by Django 5.0.2 on 2024-03-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_servicebooking_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
