# Generated by Django 5.0.2 on 2024-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_address_emailverification_delete_login_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], default='user', max_length=50),
        ),
    ]
