# Generated by Django 5.0.2 on 2024-02-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userservicerating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserServiceRating',
        ),
    ]
