# Generated by Django 5.0.2 on 2024-03-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_providerservice_address_providerservice_category_and_more'),
        ('user', '0006_feedback_service_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicebooking'),
        ),
    ]
