# Generated by Django 5.0.2 on 2024-03-23 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_currency_code_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
