# Generated by Django 5.0.1 on 2024-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_user_s_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
