# Generated by Django 5.0.2 on 2024-03-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_providergetintouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='providergetintouch',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
