# Generated by Django 5.0.2 on 2024-03-23 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_providergetintouch_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='providergetintouch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providergetintouch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
