# Generated by Django 5.0.2 on 2024-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_providergetintouch_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
    ]
