# Generated by Django 5.0.2 on 2024-03-23 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_usersystemvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystemvisit',
            name='created_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
