# Generated by Django 5.0.2 on 2024-03-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_usersystemvisit_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
