# Generated by Django 5.0.2 on 2024-03-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
    ]
